# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Kevin. Y. "Harbinger" Xiu's Personal Blog
description: Ph.D. student at Duke ECE. Interests including Machine learning, Computer Vision, Running, Marvel Comics. ;-)
github_username: jph00

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
  
waline:
  enable: false #是否开启
  serverURL: waline-server-ecru.vercel.app # Waline #服务端地址，我们这里就是上面部署的 Vercel 地址
  locale:
    placeholder: Welcome! # #评论框的默认文字
  avatar: mm # 头像风格
  meta: [nick,mail] # 自定义评论框上面的三个输入框的内容
  pageSize: 10 # 评论数量多少时显示分页
  lang: zh-cn # 语言, 可选值: en, zh-cn
  visitor: true # 文章阅读统计
  comment_count: true # 如果为 false , 评论数量只会在当前评论页面显示, 主页则不显示
  requiredFields: [nick] # 设置用户评论时必填的信息，[nick,mail]: [nick] | [nick, mail]
  libUrl: https://unpkg.com/@waline/client@v2/dist/waline.js # Set custom library cdn url
  login: enable

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
